#!/bin/bash


if [ "$1" = "-h" ]; then
  echo "version 2.0"
  echo "Help"
  echo "Usage"
  echo "sgc 'Your commit Message' -> For commit and pushing to origin master"
  echo "sgc [-OPTION]"
  echo "Options"
  echo "-u 'Your Message' -> For commit and pushing to upstream master" 
  echo "-a 'Your Message' -> For amending commit" 
  echo "fo -> For fetching and merging from origin master" 
  echo "fu -> For fetching and merging from upstream master" 
  echo "bi -> Bundle Install" 
  echo "bi -> Bundle Install" 
  exit 0

elif [ -n "$1" -a -n "$2" -a -n "$3"  ]; then
	echo "Adding All Files"
	git add .

	echo "Committing"
	git commit -m " $1 "

	echo "Pushing to origin/master"
	git push $2 $3

else
	echo "Invalid Argument"
	echo "use -h for help commands"
fi