#!/bin/bash

if [[ $1 = 'fo' ]]; then

	echo "Fetching from origin master"
	git fetch origin master

	echo "Merging origin master"
	git merge origin/master

elif [[ $1 = 'fu' ]]; then

	echo "Fetching from upstream master"
	git fetch upstream master

	echo "Merging upstream/master"
	git merge upstream/master

elif [[ $1 = "-a"  ]]; then

	git commit --amend -m " $2 "
	git push --force origin master

elif [[ $1 = '-u' ]]; then

	echo "Adding All Files"
	git add .

	echo "Committing"
	git commit -m " $1 "

	echo "Pushing to upstream master"
	git push upstream master

elif [[ $1 = '-gh' ]]; then

	echo "Adding All Files"
	git add .

	echo "Committing"
	git commit -m " $1 "

	echo "Pushing to upstream master"
	git push origin gh-pages

elif [[ $1 = 'bi' ]]; then

	echo "bundle install"
	bundle install
	echo "bower install"
	bower install

elif [ "$1" = "-h" ]; then
  echo "Help"
  echo "Usage"
  echo "sgc 'Your commit Message' -> For commit and pushing to origin master"
  echo "sgc [-OPTION]"
  echo "Options"
  echo "-u 'Your Message' -> For commit and pushing to upstream master" 
  echo "-a 'Your Message' -> For amending commit" 
  echo "fo -> For fetching and merging from origin master" 
  echo "fu -> For fetching and merging from upstream master" 
  echo "bi -> Bundle Install" 
  echo "bi -> Bundle Install" 
  exit 0

elif [ -n "$1" ]; then
	
	echo "Adding All Files"
	git add .

	echo "Committing"
	git commit -m " $1 "

	echo "Pushing to origin/master"
	git push origin master



else
	echo "Invalid Argument"
fi